<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use AppBundle\Constants\Constants;

/**
 * SoireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractRepository extends EntityRepository
{
	/**
	 * Build a paginator.
	 * @param unknown $queryBuilder
	 * @param unknown $page
	 * @param unknown $nbElmtByPage
	 */
	protected function buildPaginator($queryBuilder, $page, $nbElmtByPage)
	{
		$queryBuilder->setFirstResult(($page-1) * $nbElmtByPage)
			         ->setMaxResults($nbElmtByPage);
		
		return new Paginator($queryBuilder);
	}
	
}
