<?php

namespace AppBundle\Entity;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends AbstractRepository
{
	public function findByUserId($userId)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->leftJoin('c.owner', 'o')
			->where($qb->expr()->eq('o.id', ':userId'));
		$qb->setParameter('userId', $userId);
		
		return $qb->getQuery()->getSingleResult();
	}
}
