<?php

namespace AppBundle\Entity;

/**
 * DemandeCpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeCpRepository extends \Doctrine\ORM\EntityRepository
{
	
}
