<?php

namespace AppBundle\Entity;

/**
 * OffreCpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreCpRepository extends \Doctrine\ORM\EntityRepository
{
}
