<?php

namespace AppBundle\Entity;

/**
 * ReservationCpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationCpRepository extends \Doctrine\ORM\EntityRepository
{
}
