<?php

namespace AppBundle\Entity;

/**
 * RestrictionCpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionCpRepository extends \Doctrine\ORM\EntityRepository
{
}
